### ISSUE TITLE
Any interest in more features?

### ISSUE THREAD

**Issue by cjrh** [not-an-aardvark/git-structured-log#1]
Hi @not-an-aardvark 

Thank you for sharing this project. I've been trying to figure out how to use `git log` to generate CSV for a range of commits that includes the "files changed", "additions" and "deletions" counts, and this project was the cleanest way I found.

Just checking whether you're interested in getting new features on this project? I don't really mind either way, and I know very well how much a burden open source can become. If you just want to keep your project as-is, that's perfectly fine.

For interest sake, I made a bunch of changes in a branch of my fork:
- Can include "files changed", "additions" and "deletions" counters in the record
- Can choose json or csv output
- Upgrade args handling to use structlog & paw
- Added CLI option to refer to a specific directory path to target a repo other than `"."`
- Added CLI option to generate output in "reversed" order, i.e. starting from oldest commit to newest.

e.g. 

```bash
$ cargo run -- 'HEAD@{2 days ago}..HEAD' h,ae,an,aI,cI,df,di,dd --repo ~/Documents/<repo> -o csv --oldest-first
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/git_structured_log 
aI,ae,an,cI,dd,df,di,h
"2021-11-12T05:13:26+00:00","semantic-release-bot@martynus.net","semantic-release-bot","2021-11-12T05:13:26+00:00","2","3","9","0f58c4a"
"2021-11-12T16:32:03+10:00","caleb.hattingh@<snip>","Caleb Hattingh","2021-11-12T16:32:03+10:00","16","3","39","2d1c240"
"2021-11-12T06:33:20+00:00","semantic-release-bot@martynus.net","semantic-release-bot","2021-11-12T06:33:20+00:00","2","3","9","9398e1f"
"2021-11-12T17:12:58+10:00","49699333+dependabot[bot]@users.noreply.github.com","dependabot[bot]","2021-11-12T17:12:58+10:00","1","1","1","e893e4c"
...
```
My changes are messy, I don't have a lot of time spend on this. Anyway, the branch is here, feel free to grab what you want: https://github.com/cjrh/git-structured-log/tree/fix-lints

**Comment by not-an-aardvark** [comment]
Thanks for working on this! Personally, I don't think I have time to maintain these changes, but I'm glad the project has been useful to you. I'd be happy to link to your fork in the readme or something.

**Comment by cjrh** [comment]
Oh no worries about adding a link, I don't intend long term maintenance of my changes either.  All good :)
